#pragma once
#ifndef PROJECT_SETTINGS_H
#define PROJECT_SETTINGS_H

#define SETTING_DEBUG

#define SETTING_PROJECT_NAME		L"Project1"
#define SETTING_WINDOW_CLASS_NAME	L"Project1 window class"
#define SETTING_WINDOW_NAME			L"Project1"

#define SETTING_RESOLUTION_WIDTH	800
#define SETTING_RESOLUTION_HEIGHT	600

#define SETTING_BATCH_WIDTH 4096
#define SETTING_BATCH_HEIGHT 4096

constexpr float RES_RATIO_WIDTH = 1.f/SETTING_RESOLUTION_WIDTH;
constexpr float RES_RATIO_HEIGHT = 1.f/SETTING_RESOLUTION_HEIGHT;

#endif